### ISSUE TITLE
Ajouter une scrollbar à la fenêtre principale

### ISSUE THREAD

**Issue by frdyvn** [CEN-Nouvelle-Aquitaine/fluxcen#12]
Ajouter une scrollbar à la fenêtre principale pour dépanner les quelques personnes ayant moins de 800px de largeur d'écran et ne pouvant pas atteindre le bouton "charger les couches". Merci !

**Comment by wanderzen91** [comment]
Ok fait et installé sur le PC de Murielle (dev pas intégré au git et à la version en prod du plugin)
