### ISSUE TITLE
Gestion automatique des flux protégés

### ISSUE THREAD

**Issue by tomgachet** [CEN-Nouvelle-Aquitaine/fluxcen#13]
Intégrer la détection automatique d'un flux protégé (authcfg dans l'URL du flux)

**Comment by rmylb** [comment]
Normalement c'est déjà le cas non ? Il me semble qu'on avait parlé d'un double contrôle : 
- Première requête, si on a un 403 alors on auth
- Mais on auth que si le nom de domaine match notre serveur (pour ne pas envoyer l'auth sur d'autres serveurs).

**Comment by wanderzen91** [comment]
Un truc du genre devrait marcher en modifiant quelques petites parties supplémentaires du code, à intégrer dans la prochaine MAJ significative !

```

def displayOnWindows(type, uri, name):
	if 'opendata.cen-nouvelle-aquitaine.org' in uri:
		response = requests.get(uri)
		
		# Vérifier le code de statut de la réponse HTTP
		if response.status_code == 401:
			if len(list(k)) == 0:
				QMessageBox.question(iface.mainWindow(), u"Attention", "Veuillez ajouter une entrée de configuration d'authentification dans QGIS pour accéder aux flux CEN-NA sécurisés par un mot de passe", QMessageBox.Ok)
				raise ValueError("Veuillez ajouter une entrée de configuration d'authentification dans QGIS pour accéder aux flux CEN-NA sécurisés par un mot de passe")
		else:
			print("Le flux n'est pas protégé par un mot de passe.")
			


```

**Comment by tomgachet** [comment]
Je viens d'avoir le souci après avoir ajouté un espace de travail protégé (chirokollect) :bat: :bat:

**Comment by tomgachet** [comment]
Petite suggestion pour gérer les flux protégés!
Plutôt que mettre en dur dans le code l'URL pour tester la demande de mot de passe, ne peut-on pas envisager de le gérer depuis un fichier de config? On pourrait imaginer pouvoir mettre plusieurs URL de serveurs carto dans ce fichier sur lequel QGIS irait tester l'accès à la connexion.

**Comment by rmylb** [comment]
Oui, le mieux je pense est de mettre en config ou en dur le nom de domaine de notre Geoserver, au chargement d'un flux issue de ce domaine, s'il détecte un 403, alors il refait la requête avec l'auth.

**Comment by wanderzen91** [comment]
Amélioration intégrée à FluxCEN 3.8 !
