### ISSUE TITLE
Ajouter une section "à propos"

### ISSUE THREAD

**Issue by tomgachet** [CEN-Nouvelle-Aquitaine/fluxcen#3]
Rajout d'une section à propos avec les métadonnées du plugin ainsi qu'un résumé de toutes les sources utilisées.

**Comment by wanderzen91** [comment]
J'ai crée pour chaque plugin une section "informations" relative à la version de l'outil (accessible via le petit pictogramme bleu en bas à droite des fenêtres des plugins). C'est un fichier HTML donc on peut le mettre en forme comme on le souhaite et éventuellement intégrer les métadonnées dedans ?
