### ISSUE TITLE
Notification des nouvelles ressources disponibles

### ISSUE THREAD

**Issue by tomgachet** [CEN-Nouvelle-Aquitaine/fluxcen#6]
Il serait intéressant de connaître facilement les nouvelles couches rajoutées au chargement de FluxCEN.
A voir comment c'est possible, par exemple afficher en premier les nouvelles couches à l'ouverture?

**Comment by wanderzen91** [comment]
Alors je m'étais déjà posé la question mais je pense que c'est difficilement automatisable puisqu'on ne peut pas vraiment récupérer la date à laquelle de nouvelles lignes ont été ajoutées au csv. Il faudrait à la limite faire un petit fichier texte "nouveautés" dans lequel on renseignerait les flux les plus récents ainsi que les améliorations de l'outil mais va-t-on vraiment faire l'effort de remplir ce fichier régulièrement ?

**Comment by wanderzen91** [comment]
![image](https://user-images.githubusercontent.com/103043914/196468779-5b7f7b27-9026-4390-ab6a-95d531e711f5.png)

Voilà ce que ça pourrait donner sous forme de popup
