### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by davidmichallet** [CEN-Nouvelle-Aquitaine/fluxcen#9]
Bonjour les collégues de NA,
une petite question concernant votre Super plugin :smiley:  , quel est sa licence pour pouvoir le réutiliser chez nous ?
Merci !

**Comment by wanderzen91** [comment]
Salut David, 

Je vois avec Mikaël et je reviens vers toi dans la semaine :)

Ton ancien collègue du CEN03 😄

**Comment by wanderzen91** [comment]
On vient d'évoquer ce point en réunion de service et on se disait qu'on aurait éventuellement pu statuer tous ensemble du choix de la licence lors du prochain café SI avant de la faire valider par notre direction !

**Comment by wanderzen91** [comment]
Salut David, 

On part sur une [gplv3](https://github.com/topics/gplv3) comme vu au dernier café SIG !
